export const SET_USER = 'SET_USER';
export const SET_WEIGHTS = 'SET_WEIGHTS';
export const LOGOUT = 'LOGOUT'
export const SET_USERS = 'SET_USERS'
export const SET_EXERCISES = 'SET_EXERCISES'
export const SET_USERS_FOR_TRANSACTIONS = 'SET_USERS_FOR_TRANSACTIONS'
